### ISSUE TITLE
wrong APK ersion?

### ISSUE THREAD

**Issue by IzzySoft** [Akshayaap/TouchDroid#20]
While the APK file attached to release v1.4.0 is named `MouseRemove-1.4.0.apk`, it identifies as v1.1.0:

    package: name='com.akshayaap.mouseremote' versionCode='2' versionName='1.1.0' compileSdkVersion='32' compileSdkVersionCodename='12'

The `build.gradle` [at that tag](https://github.com/Akshayaap/MouseRemote/blob/v1.4.0/app/build.gradle#L13) also states `1.1.0` (and also `versionCode:2`). Could you please adjust that?

* `versionCode` should always be increased with each version (used by Android to tell them apart and signal for updates)
* `versionName` is for the user to see, so will be helpful with issue reports etc – and shoud be in sync with the tag name

Thanks in advance!

PS: Looking at the other releases, maybe you just misnamed the tag and the APK is fine?

**Comment by IzzySoft** [comment]
Thanks a lot! Your app is btw. available now [via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.akshayaap.mouseremote). If you wish you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme. And if you have a dedicated icon (currently your app is using the Android default icon), it can be integrated easily (as can screenshots if there are any).

**Comment by Akshayaap** [comment]
- Thanks a lot for your support. As you have said that there is default application icon,but the thing is I already have added custom icon.
- Second thing is there is little typo mistake in the link to MouseRemoteServer in your repo. so please fix that issue.
for further communication mail me at akshaykumarparmar51@gmail.com.
- Thank you.

**Comment by Akshayaap** [comment]
- will you please tell me that I am allowed to make changes [in your repo](https://apt.izzysoft.de/fdroid/index/apk/com.akshayaap.mouseremote) as per requirements.

**Comment by IzzySoft** [comment]
> I already have added custom icon.

Where can I find it? the one at `https://github.com/Akshayaap/MouseRemote/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp` is the Android default icon. I could not find another one.

> there is little typo mistake in the link to MouseRemoteServer in your repo

If it's the same one you have in your Readme, I've just fixed this now (goes live in about an hour). If not, please point out what it is and I will take care. And apologies, but I cannot communicate with Gmail accounts.

> will you please tell me that I am allowed to make changes

Sure. Most details are [described here](https://gitlab.com/IzzyOnDroid/repo/). My updater fetches new releases within 24h of your tagging them and having an APK attached to the tag. As for description, screenshots etc: you can use [Fastlane structures](https://gitlab.com/-/snippets/1895688) in your repo here to maintain them yourself, my updater then fetches them along with new releases. If you wish, I can send you a "starter package" from what is set up with my repo as PR here.

> As the new releases will be published I will need to update in your repo accordingly.

Yes, of course – they will as described. "Pickup time" usually is between 5 pm and 6 pm UTC (or rather 7 pm and 8 pm CE(S)T).

**Comment by IzzySoft** [comment]
PS: You only fixed it partially. v1.4.1 still has `versionCode: 2`. This must be increased with each release as it is what Android uses internally to tell versions apart. For technical reasons, the combination `applicationId`+ `versionCode` must be unique. Your v1.4.1 now simply replaced (woverwrote) the previous one with the same `versionCode`, and no users were informed as `versionCode` was not increased (so Android considers it the very same app and version and thus decides to not put out an update notification – and of course to not update the installed app).

**Comment by Akshayaap** [comment]
- Sorry for inconvenient. We have published another release MouseRemote-1.4.2 fixing all the problems you have specified.
- We request you to update these release in your repo as well.
- Thank you.

**Comment by IzzySoft** [comment]
Thanks @Akshayaap – I've added the new icon and ran a manually triggered update for you (the latter would have run automatically in about3 hours), so you can see what happens whenever you have a new release ready:

```
$ getRelease -vp com.akshayaap.mouseremote
com.akshayaap.mouseremote: looking for 'https://api.github.com/repos/Akshayaap/MouseRemote/releases'
com.akshayaap.mouseremote: checking tag 'v1.4.2'
com.akshayaap.mouseremote: lastRelNo set to '1.4.2', checking for files
Upstream file date (2022-09-09 12:37) is newer than ours (2022-09-07 02:00).
com.akshayaap.mouseremote: returning ['1.4.2','https://github.com/Akshayaap/MouseRemote/releases/download/v1.4.2/MouseRemote-1.4.2.apk']
com.akshayaap.mouseremote: 1.4.1/1.4.2, https://github.com/Akshayaap/MouseRemote/releases: https://github.com/Akshayaap/MouseRemote/releases/download/v1.4.2/MouseRemote-1.4.2.apk
- Grabbing update for com.akshayaap.mouseremote: OK
- Checking 'com.akshayaap.mouseremote_4.apk' for libraries and malware …
com.akshayaap.mouseremote: check if repo contains FUNDING.yml
com.akshayaap.mouseremote: looking for 'https://api.github.com/repos/Akshayaap/MouseRemote/contents/.github'
com.akshayaap.mouseremote: Github reports "Not Found" for https://api.github.com/repos/Akshayaap/MouseRemote/contents/.github
com.akshayaap.mouseremote: looking for 'https://api.github.com/repos/Akshayaap/MouseRemote/contents/'
com.akshayaap.mouseremote: no FUNDING.yml detected.
com.akshayaap.mouseremote: no Fastlane configured, skipping Fastlane check.
```

So the new tag was found, the APK attached to it was fetched, passed all checks – and will go live with the next sync. My offer for a "Fastlane starter package" still stands :wink:

**Comment by Akshayaap** [comment]
- I got it. Will you please Explain in detail how can I set up Fastlane Structures.

**Comment by IzzySoft** [comment]
I've linked my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) above already, everything's there. Plus some [formatting hints for `full_description.txt` here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). I'll send you a starter package in a few minutes to make it easier for you.

**Comment by Akshayaap** [comment]
- I have changed package name from com.akshayaap.museremote to com.akshayaap.touchdroid. How do I make changed in your repository as per the changes.
- I haven't pushed the updates in GitHub yet.

**Comment by IzzySoft** [comment]
A new `applicationId` means a different app (users also cannot simply "update" the existing app to the renamed one) – which means we'll need to list it as new app. Doing so, we can insert a note to the old entry stating it's discontinued and link to the new one. Then, giving users a decent time to "move over", the old record should be deleted (e.g. at the end of the year).

If there are settings / data, I hope the current version offers a way to export those, and the new one has means to import that, to ease migration?
