### ISSUE TITLE
Do you mind if I write a request to be added to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [Akshayaap/TouchDroid#35]

**Comment by Akshayaap** [comment]
will you please elaborate ?

**Comment by Akshayaap** [comment]
> Do you mind if I write a request to be added to F-Droid?

sure !!

**Comment by Akshayaap** [comment]
> Do you mind if I write a request to be added to F-Droid?

You can do it.

**Comment by Akshayaap** [comment]
AuthorName:   Akshay Parmar
AuthorEmail:    [akshaykumarparmar51@gmail.com](akshaykumarparmar51@gmail.com)
AuthorWebSite:  [Akshayaap.github.io](Akshayaap.github.io)
WebSite:  [Akshayaap.github.io](Akshayaap.github.io)
IssueTracker:  
Donate:  [https://paypal.me/akshayaap](https://paypal.me/akshayaap)
Bitcoin: 
LiberaPay:

**Comment by Akshayaap** [comment]
Yes

**Comment by Akshayaap** [comment]
What's the updates ?

**Comment by Akshayaap** [comment]
Please contact me regarding this to this email [akshaykumarparmar51@gmail.com](mailto:akshaykumarparmar51@gmail.com)

**Comment by Akshayaap** [comment]
okay thanks

**Comment by IzzySoft** [comment]
@vitaminncpp now that your app arrived on F-Droid.org (congrats!), do you wish me to [keep it in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.akshayaap.touchdroid)? Usually, at this point apps are removed here again after a decent overlap of about 2 weeks – unless explicitly requested otherwise.

**Comment by vitaminncpp** [comment]
- Thank you.
- Let it be there if you want to.

**Comment by IzzySoft** [comment]
Thanks! I'll take that as a "keep request" then and mark the app accordingly. Btw: Will you add some screenshots to your fastlane structures one day? Looks a bit naked without :wink:

**Comment by vitaminncpp** [comment]
> Will you add some screenshots to your fastlane structures one day?
Okay I will do that.
