### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by IzzySoft** [Akshayaap/TouchDroid#38]
I've just noticed you've changed the `applicationId` – as this caused updates to fail in my repo, and will cause them to fail at F-Droid.org as well. If you want to stick with the new name, please consider:

* updating description etc. in Fastlane accordingly
* updating the name in the Readme
* apply for a new app listing with F-Droid (renaming is not possible; a different `applicationId` means a different app)

While on it, adding some screenshots would be nice. And while discussing it: Do you want your app to stay in my repo once you've got the newly named one listed at F-Droid.org? I've just established it there with the new name and added a note to the original one's description to make users aware they have to uninstall and reinstall if they want to receive updates again.

**Comment by IzzySoft** [comment]
PS: Note that I **replaced** the app in my repo, so the link from your Readme leads to a 404. My repo meanwhile holds TouchDroid.

**Comment by Akshayaap** [comment]
Thank you

**Comment by Akshayaap** [comment]
I noticed that my readme and description is not being updated to your app repository as I make update in my github repository.

**Comment by IzzySoft** [comment]
It is – but not before you make the next release. Fastlane is checked whenever a new release is pulled. Your last change to the description was on January 2nd, your last release on December 31st. I've just triggered an update manually now, so the next sync should reflect it.

**Comment by Akshayaap** [comment]
Ok Thank you.
